### NumPy Array
without index & label
* Vectors: 1-d arrays 向量: 一維陣列 變數名稱`X`: `X[0]`, `X[1]`,`X[2]`,..., `X[n-1]`
* Matrices: 2-d arrays 矩陣: 二維陣列 變數名稱`Xn×m`，`i` = 0, 1,..., n-1 與 `j` = 0, 1,..., m-1

In [1]:
import numpy as np

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [13]:
a*b

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [14]:
# Return evenly spaced values within a given interval, 建立相同等距的陣列
# np.arrange(start, end, step), start及step可省略
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:

np.ones((4,5)))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
a = np.array([[1,2],[3,4]])
b = np.eye(2)
a*b

array([[1., 0.],
       [0., 4.]])

In [8]:
#在一定範圍內來均勻地撒點(起點,終點,撒點數)
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
# 隨機抽樣-均勻分配
# np.random.rand(k, r), 從均勻分配[0, 1)間取出 r 組各個 k 個值, r預設為1

np.random.rand(2,2)

array([[0.73272889, 0.35530856],
       [0.68881774, 0.16654471]])

In [20]:
# 隨機抽樣-常態分配
# np.random.randn(k, r), 從標準常態分配取出 r 組各 k 個值, r預設為1

np.random.randn(5,5)

array([[ 0.18185876, -1.55919686, -0.17693236,  0.62847524, -1.07703785],
       [-0.4896284 ,  2.91712215,  0.73767012, -0.6945694 ,  1.72360948],
       [ 0.17379365, -1.00840438,  0.22268383, -1.37606136,  1.6788245 ],
       [ 1.01541862,  0.52329026, -0.2081475 ,  1.07791584, -0.40690831],
       [ 0.60947332, -0.5916771 ,  0.79148428,  1.80214587,  0.82819165]])

In [22]:
#常態分配取整數
# np.random.randn(start, end, n), 從start到end-1, 取n個值

np.random.randint(1,100,100)

array([19, 75, 18, 58, 95, 90, 80, 97, 46, 96,  4,  4, 60, 38, 78, 56, 10,
       72, 80, 39, 91, 50, 92, 12, 68, 31, 81, 75, 38, 13, 31, 69, 20, 59,
       23, 10, 91, 56, 42, 91, 98, 84, 66, 90, 50, 27, 73, 77, 80, 44,  3,
       29, 24, 79, 67, 41, 20, 27, 65, 97,  5, 29, 25, 56, 84, 90, 43, 42,
       13, 91, 83, 82, 29, 47, 49, 26, 19, 79, 63,  8, 10, 19, 89, 58, 25,
       69, 83, 94, 35, 72, 25, 58, 14, 21, 16, 99, 94, 59, 43, 77])

In [25]:
# randint: return random integers from low (inclusive) to high (exclusive)

ranarr = np.random.randint(0,50,10)
ranarr

array([30, 39, 31,  9, 11,  2,  4, 39, 49,  2])

In [29]:
#回傳最大值
ranarr.max()

49

In [28]:
#回傳最大值的index
ranarr.argmax()

8

In [30]:
ranarr.sum()

216

In [32]:
# Square Roots
np.sqrt(ranarr)

array([5.47722558, 6.244998  , 5.56776436, 3.        , 3.31662479,
       1.41421356, 2.        , 6.244998  , 7.        , 1.41421356])

## Pandas

數據分析套件，提供了Series與DataFrame兩種主要的數據結構。Series 是用來處理時間序列相關的資料，它的結構類似有索引 (Index) 的一維陣列。DataFrame則是用來處理表格化的資料，是具有列和欄的二維陣列，類似關聯式資料庫 (Relational Database, RDB) 的形式。

[Reference] <br/>
Pandas https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html

In [33]:
import pandas as pd

#### Series 一維陣列資料結構
Series裡有兩個重要的屬性：索引鍵（index）和對應的值（values）。透過這兩個屬性可以取到Series裡的資料。
- index：索引鍵。
- values：值。

In [34]:
ser = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [35]:
ser.index

Index(['USA', 'Germany', 'USSR', 'Japan'], dtype='object')

In [36]:
ser['Japan']

4

In [37]:
ser * 2

USA        2
Germany    4
USSR       6
Japan      8
dtype: int64

In [38]:
ser[ser > 3]

Japan    4
dtype: int64

In [39]:
ser.isnull()

USA        False
Germany    False
USSR       False
Japan      False
dtype: bool

In [40]:
series = pd.Series([1, 2, 3])
series

0    1
1    2
2    3
dtype: int64

### 常用函數
- len()
- size()
- count()
- unique()
- nunique()
- value_counts()
- sort_values()
- sort_index()

### Create an DataFrame

`pd.DataFrame(data=None, index=None, columns=None)`

#### DataFrame 二維陣列資料結構
最基本的三個屬性包括：列索引鍵（index）、欄索引鍵（columns）和其值（values）

In [41]:
## randn(row, column): return a sample from the "standard normal" distribution. 

df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A -0.533448  0.064446 -1.603483  0.926210
B -1.775300  0.893145  1.257461 -1.285469
C  1.588733  0.933704 -0.754416  1.066589
D -0.343310  0.088166  0.663532  0.199944
E -1.878127  2.031488 -1.457064  0.241868

In [42]:
#欄位資訊
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [43]:
#包含欄位名稱
df.head()

W         X         Y         Z
A -0.533448  0.064446 -1.603483  0.926210
B -1.775300  0.893145  1.257461 -1.285469
C  1.588733  0.933704 -0.754416  1.066589
D -0.343310  0.088166  0.663532  0.199944
E -1.878127  2.031488 -1.457064  0.241868

In [44]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [45]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [46]:
#描述性統計資料
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean  -0.588290  0.802190 -0.378794  0.229828
std    1.403133  0.804804  1.281347  0.933043
min   -1.878127  0.064446 -1.603483 -1.285469
25%   -1.775300  0.088166 -1.457064  0.199944
50%   -0.533448  0.893145 -0.754416  0.241868
75%   -0.343310  0.933704  0.663532  0.926210
max    1.588733  2.031488  1.257461  1.066589

In [47]:
#用X欄排序
df.sort_values(by='X') 

W         X         Y         Z
A -0.533448  0.064446 -1.603483  0.926210
D -0.343310  0.088166  0.663532  0.199944
B -1.775300  0.893145  1.257461 -1.285469
C  1.588733  0.933704 -0.754416  1.066589
E -1.878127  2.031488 -1.457064  0.241868

In [55]:
#倒序
df.sort_values(by='X',ascending=False)

W         X         Y         Z
CO -1.878127  2.031488 -1.457064  0.241868
WY  1.588733  0.933704 -0.754416  1.066589
NY -1.775300  0.893145  1.257461 -1.285469
OR -0.343310  0.088166  0.663532  0.199944
CA -0.533448  0.064446 -1.603483  0.926210

In [48]:
## create a new column
df['new'] = df['W'] + df['Y']
df

W         X         Y         Z       new
A -0.533448  0.064446 -1.603483  0.926210 -2.136931
B -1.775300  0.893145  1.257461 -1.285469 -0.517839
C  1.588733  0.933704 -0.754416  1.066589  0.834317
D -0.343310  0.088166  0.663532  0.199944  0.320222
E -1.878127  2.031488 -1.457064  0.241868 -3.335191

In [53]:
## drop column(axis=1)
df.drop('new',axis=1,inplace = True) #一定要寫axis參數跟inplace 表永久置換，不然會以為是暫時的
df

W         X         Y         Z
A -0.533448  0.064446 -1.603483  0.926210
B -1.775300  0.893145  1.257461 -1.285469
C  1.588733  0.933704 -0.754416  1.066589
D -0.343310  0.088166  0.663532  0.199944
E -1.878127  2.031488 -1.457064  0.241868

In [54]:
df.rename(index={'A':'CA', 'B':'NY', 'C':'WY', 'D':'OR', 'E':'CO'}, inplace=True)
df

W         X         Y         Z
CA -0.533448  0.064446 -1.603483  0.926210
NY -1.775300  0.893145  1.257461 -1.285469
WY  1.588733  0.933704 -0.754416  1.066589
OR -0.343310  0.088166  0.663532  0.199944
CO -1.878127  2.031488 -1.457064  0.241868

### Selection

列索引鍵取值, loc是location的縮寫, iloc是index location的縮寫

* df.loc[row, col]
* df.iloc[row, col]
* df[col]
* df[a:b]  使用row編號選取row
* df[col][row]

In [56]:
# Use label to select row
df.loc['CA']

W   -0.533448
X    0.064446
Y   -1.603483
Z    0.926210
Name: CA, dtype: float64

In [57]:
# Or use position to select row
df.iloc[2]

W    1.588733
X    0.933704
Y   -0.754416
Z    1.066589
Name: WY, dtype: float64

In [58]:
df['Z']

CA    0.926210
NY   -1.285469
WY    1.066589
OR    0.199944
CO    0.241868
Name: Z, dtype: float64

In [59]:
df.Z

CA    0.926210
NY   -1.285469
WY    1.066589
OR    0.199944
CO    0.241868
Name: Z, dtype: float64

In [60]:
df[['Z']]

Z
CA  0.926210
NY -1.285469
WY  1.066589
OR  0.199944
CO  0.241868

In [65]:
df[1:3]

W         X         Y         Z
NY -1.775300  0.893145  1.257461 -1.285469
WY  1.588733  0.933704 -0.754416  1.066589

In [62]:
df['Z']['NY']

-1.2854688847961937

In [68]:
df[df['Y']>0]

W         X         Y         Z
NY -1.77530  0.893145  1.257461 -1.285469
OR -0.34331  0.088166  0.663532  0.199944

#### Missing data 遺失值
NaN（Not a number）在Python是一個特殊的值，只能用函數來檢查，不能用等號檢查，即使用np.NaN == np.NaN都是False。

In [69]:
df['V'] = [1, 2, np.nan, np.nan, 5]
df

W         X         Y         Z    V
CA -0.533448  0.064446 -1.603483  0.926210  1.0
NY -1.775300  0.893145  1.257461 -1.285469  2.0
WY  1.588733  0.933704 -0.754416  1.066589  NaN
OR -0.343310  0.088166  0.663532  0.199944  NaN
CO -1.878127  2.031488 -1.457064  0.241868  5.0

In [70]:
# check for null value
df.isnull()

W      X      Y      Z      V
CA  False  False  False  False  False
NY  False  False  False  False  False
WY  False  False  False  False   True
OR  False  False  False  False   True
CO  False  False  False  False  False

In [71]:
df.isnull().sum()

W    0
X    0
Y    0
Z    0
V    2
dtype: int64

In [72]:
df.isnull().sum().sum()

2

In [73]:
df.isnull().any(axis=1)

CA    False
NY    False
WY     True
OR     True
CO    False
dtype: bool

In [74]:
df[df.isnull().any(axis=1)]

W         X         Y         Z   V
WY  1.588733  0.933704 -0.754416  1.066589 NaN
OR -0.343310  0.088166  0.663532  0.199944 NaN

### Handle missing value
* ignore
* drop
* fill in

In [75]:
df.dropna()

W         X         Y         Z    V
CA -0.533448  0.064446 -1.603483  0.926210  1.0
NY -1.775300  0.893145  1.257461 -1.285469  2.0
CO -1.878127  2.031488 -1.457064  0.241868  5.0

In [76]:
df.fillna(value = 'replace')

W         X         Y         Z        V
CA -0.533448  0.064446 -1.603483  0.926210      1.0
NY -1.775300  0.893145  1.257461 -1.285469      2.0
WY  1.588733  0.933704 -0.754416  1.066589  replace
OR -0.343310  0.088166  0.663532  0.199944  replace
CO -1.878127  2.031488 -1.457064  0.241868      5.0

In [77]:
df['V'].fillna(value = df['V'].mean())

CA    1.000000
NY    2.000000
WY    2.666667
OR    2.666667
CO    5.000000
Name: V, dtype: float64

In [78]:
df['V'].max()

5.0

In [79]:
df['X'].sum()

4.010949208803867

## HW

1. 利用下面的資料建立DataFrame <br/>
list1 = [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]] <br/>
columns = ['Math', 'English', 'History'] <br/>
index=['Simon','Allen','Jimmy','Peter']

In [34]:
import pandas as pd

list1 = [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]]
columns = ['Math', 'English', 'History']
index=['Simon','Allen','Jimmy','Peter']

grade = pd.DataFrame(data=list1,index=index,columns=columns)
grade

Math  English  History
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60

In [43]:
#取出數學>60 且英文>85 的資料, 並以DataFrame的方式呈現
m = grade['Math']>60
e = grade['English']>85

grade[(m & e)]

Math  English  History
Jimmy    70       90       88

In [2]:
#計算各科的平均數
grade.mean()

Math       72.5
English    67.5
History    64.0
dtype: float64

In [15]:
#依各科分數來個別排名
grade.rank()

Math  English  History  Gender
Simon   4.0      2.0      1.0     3.0
Allen   1.0      3.0      3.0     1.0
Jimmy   2.0      4.0      4.0     3.0
Peter   3.0      1.0      2.0     3.0

In [12]:
#新增性別資料 Gender = 'M'.'F','M','M'

grade['Gender'] = ['M','F','M','M']
grade

Math  English  History Gender
Simon    90       60       33      M
Allen    50       70       75      F
Jimmy    70       90       88      M
Peter    80       50       60      M

In [13]:
#性別的類別各出現幾次？

grade['Gender'].value_counts()

M    3
F    1
Name: Gender, dtype: int64

In [44]:
#算出每位同學的平均分數，再用平均分數排名

grade['Average'] = grade.mean(axis=1).round()
grade['Rank'] = grade.Average.rank(method='first',ascending=False)
grade.sort_values(by='Rank')

Math  English  History  Average  Rank
Jimmy    70       90       88     83.0   1.0
Allen    50       70       75     65.0   2.0
Peter    80       50       60     63.0   3.0
Simon    90       60       33     61.0   4.0